# Generated by Django 5.0.9 on 2024-12-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_name', models.CharField(max_length=255)),
                ('num_of_tasks', models.IntegerField()),
                ('icon', models.BinaryField(blank=True, max_length='max', null=True)),
            ],
        ),
    ]
