# Generated by Django 5.0.9 on 2024-12-16 10:55

from django.db import migrations,models
import os

def load_badges(apps, schema_editor):
    Badge = apps.get_model('badge', 'badge')
    image_folder = './badge/static/badge/img'  # Replace with the actual path
    badge_names = [
        "Task Starter",
        "Diligent Worker",
        "Task Master",
        "Rising Star",
        "Goal Crusher",
        "Master Tasker",
        "Legendary Contributor",
        "Task Overlord",
        "Ultimate Performer"
    ]
    task_num=[1,10,30,50,100,150,200,300,400]
    for idx, image_name in enumerate(os.listdir(image_folder)):
        if image_name.endswith('.png'):
            if idx < len(badge_names):  # Prevent index out of range errors
                image_path = os.path.join(image_folder, image_name)
                badge_name = badge_names[idx]
                num_of_tasks = task_num[idx]
                
                with open(image_path, 'rb') as image_file:
                    image_data = image_file.read()
                    Badge.objects.create(
                        badge_name=badge_name,
                        num_of_tasks=num_of_tasks,
                        icon=image_data,
                    )
class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.BinaryField(null=True, blank=True),
        ),
        migrations.RunPython(load_badges),
    ]
