# Generated by Django 5.0.9 on 2024-12-21 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Invitation', '0001_initial'),
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='environment.environment'),
        ),
    ]
