# Generated by Django 5.0.9 on 2024-12-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invitation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='receiver_id',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='sender_id',
            new_name='sender',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='invitation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
