# Generated by Django 5.0.9 on 2024-12-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='environment',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
