# Generated by Django 5.0.9 on 2024-11-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_environment_admin_table'),
        ('task', '0001_initial'),
        ('users', '0003_alter_login_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='environment.table'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='users.login'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='users.login'),
        ),
    ]
