# Generated by Django 5.0.9 on 2024-11-30 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'deadline']},
        ),
    ]
