# Generated by Django 5.0.9 on 2024-11-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_environment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assigned',
            new_name='assigned_to',
        ),
    ]
