# Generated by Django 5.0.9 on 2024-11-28 10:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_rename_assigned_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
