# Generated by Django 5.0.9 on 2024-12-19 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_initial'),
        ('task', '0003_alter_task_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.table'),
        ),
    ]
