# Generated by Django 5.0.9 on 2024-12-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default=2, max_length=20),
        ),
    ]
