# Generated by Django 5.0.9 on 2024-12-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
