# Generated by Django 5.0.9 on 2024-11-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_task_start_in_alter_task_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='start_in',
            new_name='start_date',
        ),
    ]
