# Generated by Django 5.0.9 on 2024-12-19 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0007_usercanaccess'),
        ('task', '0005_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='environment.table'),
        ),
    ]
