# Generated by Django 5.0.9 on 2024-12-02 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_alter_task_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['priority', 'deadline']},
        ),
    ]
