# Generated by Django 5.0.9 on 2024-12-11 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['deadline']},
        ),
    ]
