# Generated by Django 5.1.4 on 2024-12-17 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('environment_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('is_private', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'environment',
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('search_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'search_history',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'table',
            },
        ),
    ]
