# Generated by Django 5.0.9 on 2024-11-28 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
        ('users', '0003_alter_login_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='admin_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_environments', to='users.login'),
        ),
        migrations.AlterField(
            model_name='table',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tables', to='users.login'),
        ),
    ]
