# Generated by Django 5.0.9 on 2024-11-28 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table',
        ),
    ]
