# Generated by Django 5.0.9 on 2024-11-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='environment',
            table='environment',
        ),
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
