# Generated by Django 5.0.9 on 2024-11-28 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0002_delete_table'),
        ('users', '0003_alter_login_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_environments', to='users.login'),
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=255)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='environment.environment')),
                ('user_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tables', to='users.login')),
            ],
        ),
    ]
