# Generated by Django 5.0.9 on 2024-12-02 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_environment_admin_alter_table_user_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='user_login',
        ),
    ]
