# Generated by Django 5.0.9 on 2024-11-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_environment_admin_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='environment',
            table='environment',
        ),
        migrations.AlterModelTable(
            name='table',
            table='table',
        ),
    ]
