# Generated by Django 5.0.9 on 2024-12-19 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_remove_table_user_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCanAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_accessibility', models.CharField(choices=[('Participant', 'Participant'), ('subadmin', 'subadmin'), ('Admin', 'Admin')], max_length=20)),
                ('invitation_status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to='environment.environment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_can_access',
                'unique_together': {('user', 'environment')},
            },
        ),
    ]
