# Generated by Django 5.0.9 on 2024-12-14 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0004_remove_table_user_login'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='environment_search_historty',
            fields=[
                ('search_history_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=255, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_search_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
