# Generated by Django 5.0.9 on 2024-12-14 17:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0005_environment_search_historty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='environment_search_historty',
            new_name='SearchHistory',
        ),
        migrations.AlterModelTable(
            name='searchhistory',
            table='search_history',
        ),
    ]
