name: Deploy to Azure

on:
  push:
    branches:
      - main  #trigger for main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name taskmate2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: taskmate2.azurecr.io/taskmate:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set \
            --name TaskmateHello \
            --resource-group DockerTaskMate \
            --docker-custom-image-name taskmate2.azurecr.io/taskmate2:v1 \
            --registry-login-server taskmate2.azurecr.io \
            --registry-username taskmate2 \
            --registry-password "lCHEHLcUfgzeiUg+k7LD018QTccSbgLl8xuYeX+XwA+ACRAGUVGi"
