name: Deploy to Azure

on:
  push:
    branches:
      - main  #trigger for main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      ACTIONS_RUNNER_DEBUG: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: |
          az acr login --name elcontainer

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: elcontainer.azurecr.io/taskmate:v1

      - name: Deploy to Azure Web App
        run: |  
          az webapp config container set \
            --name TaskMateHello \
            --os-type Linux \
            --cpu 1 \
            --memory 1 \
            --resource-group TaskMate \
            --name taskmate-container \
            --image elcontainer.azurecr.io/taskmate:v1 \
            --registry-username elcontainer \
            --registry-password uALXb5olgOUL7LQnkFxFRDn5xadIlHbTc+9fWzVpJT+ACRC9EQQ5 \
            --registry-login-server elcontainer.azurecr.io \
            --ip-address Public \
            --dns-name-label taskmate-dns \
            --ports 8000
