# Generated by Django 5.0.9 on 2024-11-19 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_login_password'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='users_login',
        ),
    ]
