# Generated by Django 5.0.9 on 2024-11-29 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_login_age_login_badge_name_login_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='age',
        ),
        migrations.RemoveField(
            model_name='login',
            name='badge_name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='name',
        ),
        migrations.RemoveField(
            model_name='login',
            name='phone_num',
        ),
        migrations.RemoveField(
            model_name='login',
            name='theme_is_light',
        ),
        migrations.AlterField(
            model_name='login',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='login',
            table='users_login',
        ),
    ]
