# Generated by Django 5.0.9 on 2024-11-30 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_login_groups_login_is_active_login_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='login',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='login',
            name='is_staff',
        ),
    ]
