# Generated by Django 5.0.9 on 2024-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_login_is_active_remove_login_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='login',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
