# Generated by Django 5.0.9 on 2024-11-30 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('environment', '0003_alter_environment_admin_alter_table_user_login'),
        ('task', '0003_alter_task_assigned_to_alter_task_created_by'),
        ('users', '0010_alter_login_managers_rename_name_login_username_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
